FROM tomcat:8.5

LABEL maintainer="ioexcept@gmail.com"
LABEL version="GoatLivesMatter:Service:1.1"

ADD service.war /usr/local/tomcat/webapps/
ADD https://repo1.maven.org/maven2/mysql/mysql-connector-java/5.1.44/mysql-connector-java-5.1.44.jar /usr/local/tomcat/lib/
