#!/bin/bash


git checkout docker
git pull origin docker

cd _docker

rm -rf glm.war 

docker-compose down

cd ../lesson8
mvn clean package
cp target/lesson8.war ../_docker/glm.war
cd ../_docker


docker build -t trasely .

docker-compose up -d && docker-compose logs -f









