version: '3'
services:
  mysql:
    image: mysql/mysql-server:5.5
    container_name: mysql
    tty: true
    stdin_open: true
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - /opt/mysql/datadir:/var/lib/mysql
      
