#!/bin/bash
echo "building GoatLivesMatter"
echo "current directory"
pwd
echo "changing to lesson 9 directory"
cd ../
pwd
cd lesson9
pwd
mvn clean package
cp webapp/target/webapp.war ../lesson11/webapp
cp service/target/service.war ../lesson11/service
echo "changing back to lesson11 directory"
cd ../
pwd
cd lesson11
pwd
