version: '3.2'
services:
  webapp:
    image: glm:webapp
    container_name: webapp
    tty: true
    stdin_open: true
    restart: always
    depends_on:
      - service
    ports:
      - 80:8080
  service:
    image: glm:service
    container_name: service
    tty: true
    stdin_open: true
    restart: always
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql/mysql-server:5.5
    container_name: mysqldb
    tty: true
    stdin_open: true
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - /opt/mysql/datadir:/var/lib/mysql

