version: '3'
services:
  tomcat:
    image: trasely
    container_name: tcat
    tty: true
    stdin_open: true
    restart: always
    ports:
      - 80:8080
    depends_on:
      - mysql
      
  mysql:
    image: mysql/mysql-server:5.5
    container_name: mysql
    tty: true
    stdin_open: true
    restart: always
    ports:
      - 3306:3306
      
#docker pull mysql/mysql-server
