FROM tomcat:8.5-jdk8-corretto

ADD https://repo1.maven.org/maven2/mysql/mysql-connector-java/5.1.44/mysql-connector-java-5.1.44.jar /usr/local/tomcat/lib/mysql-connector-java-5.1.44.jar

copy glm.war /usr/local/tomcat/webapps/glm.war




